version: '2'

services:
  isucon_app:
      build: ./app
      ports:
          - "80:80"
          - "25"
      command: bash
      environment:
          - TZ=Asia/Tokyo
      links:
          - isucon_db:db.com
  isucon_db:
      image: mysql:5.7
      environment:
          - TZ=Asia/Tokyo
          - MYSQL_ROOT_PASSWORD=isucon
          - MYSQL_DATABASE=isubata
      ports:
          - "3306:3306"
